import json, os

base = 'pipeline/recipes/'

# Translation dictionary for all 725 unique ingredient items
TRANSLATIONS = {
    "0% Fat Greek Yoghurt⁣": "Iogurte Grego 0% de Gordura",
    "10% Fat Pork Mince": "Carne Picada de Porco 10% de Gordura",
    "5% Fat Beef Mince": "Carne Picada de Vaca 5% de Gordura",
    "5% Fat Greek Yoghurt": "Iogurte Grego 5% de Gordura",
    "5% Fat Pork Mince": "Carne Picada de Porco 5% de Gordura",
    "50% Reduced-Fat Cheddar⁣": "Cheddar com 50% Menos Gordura",
    "70% Dark Chocolate": "Chocolate Negro 70%",
    "Ackee": "Ackee",
    "Agave Nectar": "Néctar de Agave",
    "Aleppo Pepper": "Pimenta de Aleppo",
    "Almond": "Amêndoa",
    "Almond Butter": "Manteiga de Amêndoa",
    "Almond Extract": "Extrato de Amêndoa",
    "Almond Milk": "Leite de Amêndoa",
    "Anchovies In Olive Oil": "Anchovas em Azeite",
    "Anchovy": "Anchova",
    "Apple & Blueberry Quaker Oats Sachet": "Saqueta de Aveia Quaker de Maçã e Mirtilo",
    "Apple Cider Vinegar": "Vinagre de Cidra de Maçã",
    "Apple Juice": "Sumo de Maçã",
    "Asparagus": "Espargos",
    "Avocado": "Abacate",
    "Baby Corn": "Mini Milho",
    "Baby Gem Lettuce": "Alface Baby Gem",
    "Baby Potato": "Batata Baby",
    "Baby Spinach": "Espinafres Baby",
    "Bacon": "Bacon",
    "Bacon Lardons": "Lardons de Bacon",
    "Baked Bean": "Feijão Cozido",
    "Baking Powder": "Fermento em Pó",
    "Balsamic Vinegar": "Vinagre Balsâmico",
    "Banana": "Banana",
    "Basil": "Manjericão",
    "Basmati Rice": "Arroz Basmati",
    "Bavette Steak": "Bife de Fraldinha",
    "Bean": "Feijão",
    "Beansprouts": "Rebentos de Soja",
    "Beef Mince": "Carne Picada de Vaca",
    "Beef Stock": "Caldo de Carne",
    "Bicarbonate of Soda": "Bicarbonato de Sódio",
    "Biscoff Spread": "Creme Biscoff",
    "Black Bean": "Feijão Preto",
    "Black Mustard Seed": "Sementes de Mostarda Preta",
    "Black Olive": "Azeitona Preta",
    "Black Pepper": "Pimenta Preta",
    "Black Peppercorn": "Grãos de Pimenta Preta",
    "Black Sesame Seed": "Sementes de Sésamo Preto",
    "Black Treacle": "Melaço Negro",
    "Blanched Hazelnuts": "Avelãs Peladas",
    "Blueberry": "Mirtilo",
    "Boiling Water": "Água a Ferver",
    "Boneless Skinless Chicken Thigh": "Coxa de Frango sem Osso e sem Pele",
    "Bread": "Pão",
    "Breadcrumb": "Pão Ralado",
    "Brie": "Brie",
    "Broccoli": "Brócolos",
    "Brown Lentil": "Lentilha Castanha",
    "Brown Sauce": "Molho Castanho",
    "Brown Sugar": "Açúcar Mascavado",
    "Bucatini": "Bucatini",
    "Bulgur Wheat": "Trigo Bulgur",
    "Butter": "Manteiga",
    "Butter Beans": "Feijão Manteiga",
    "Buttermilk": "Leitelho",
    "Cabbage": "Couve",
    "Callaloo": "Callaloo",
    "Campanelle": "Campanelle",
    "Cannellini Bean": "Feijão Cannellini",
    "Capers": "Alcaparras",
    "Carrot": "Cenoura",
    "Cashew Nut": "Castanha de Caju",
    "Caster Sugar": "Açúcar Fino",
    "Cauliflower": "Couve-Flor",
    "Cavolo Nero": "Couve Cavolo Nero",
    "Celery": "Aipo",
    "Chard": "Acelga",
    "Chargrilled Chicken Seasoning": "Tempero de Frango Grelhado",
    "Cheddar Cheese": "Queijo Cheddar",
    "Cherry Tomatoes": "Tomates Cherry",
    "Chestnut Mushroom": "Cogumelos Castanhos",
    "Chia Seed": "Sementes de Chia",
    "Chicken Breast": "Peito de Frango",
    "Chicken Mince": "Frango Picado",
    "Chicken Stock": "Caldo de Frango",
    "Chicken Thigh": "Coxa de Frango",
    "Chickpea Flour": "Farinha de Grão-de-Bico",
    "Chickpeas": "Grão-de-Bico",
    "Chilli": "Malagueta",
    "Chilli Flakes": "Flocos de Malagueta",
    "Chilli Jam": "Compota de Malagueta",
    "Chilli Oil": "Óleo de Malagueta",
    "Chilli Powder": "Pimentão Picante",
    "Chinese Black Vinegar": "Vinagre Preto Chinês",
    "Chinese Dark Soy Sauce": "Molho de Soja Escuro Chinês",
    "Chinese Five-Spice": "Cinco Especiarias Chinesas",
    "Chipotle Chilli Flake": "Flocos de Chipotle",
    "Chipotle Paste": "Pasta de Chipotle",
    "Chive": "Cebolinho",
    "Chocolate Protein Powder": "Proteína em Pó de Chocolate",
    "Chopped Nut": "Frutos Secos Picados",
    "Chopped Tomatoes": "Tomates Picados",
    "Chorizo": "Chouriço",
    "Choy Sum": "Choy Sum",
    "Cinnamon": "Canela",
    "Cocoa Powder": "Cacau em Pó",
    "Coconut Flake": "Flocos de Coco",
    "Coconut Milk": "Leite de Coco",
    "Coconut Oil": "Óleo de Coco",
    "Coconut Yoghurt": "Iogurte de Coco",
    "Cod": "Bacalhau",
    "Cold Water": "Água Fria",
    "Conchiglie": "Conchiglie",
    "Conchiglioni": "Conchiglioni",
    "Cooked Basmati Rice": "Arroz Basmati Cozido",
    "Cooked Black Beans": "Feijão Preto Cozido",
    "Cooked Brown Rice": "Arroz Integral Cozido",
    "Cooked Butter Beans": "Feijão Manteiga Cozido",
    "Cooked Chicken": "Frango Cozido",
    "Cooked Chicken Breast": "Peito de Frango Cozido",
    "Cooked Jasmine Rice": "Arroz Jasmine Cozido",
    "Cooked Kidney Beans": "Feijão Vermelho Cozido",
    "Cooked Lentil": "Lentilhas Cozidas",
    "Cooked Mixed Grains": "Cereais Mistos Cozidos",
    "Cooked Puy Lentils": "Lentilhas Puy Cozidas",
    "Cooked Quinoa": "Quinoa Cozida",
    "Cooked Quinoa and Rice": "Quinoa e Arroz Cozidos",
    "Cooked Rice": "Arroz Cozido",
    "Cooked Sushi Rice": "Arroz de Sushi Cozido",
    "Coriander": "Coentros",
    "Coriander Seed": "Sementes de Coentros",
    "Cornflour": "Farinha Maizena",
    "Cornichon": "Cornichon",
    "Cottage Cheese": "Queijo Cottage",
    "Courgette": "Courgette",
    "Couscous": "Cuscuz",
    "Cream Cheese": "Queijo Creme",
    "Crisps": "Batatas Fritas de Pacote",
    "Crispy Chilli Oil": "Óleo de Malagueta Crocante",
    "Crispy Fried Onion": "Cebola Frita Crocante",
    "Crispy Shallot": "Chalota Crocante",
    "Crunchy Nut Cornflakes": "Cereais Crunchy Nut",
    "Crunchy Peanut Butter": "Manteiga de Amendoim Crocante",
    "Crushed Frozen Raspberries": "Framboesas Congeladas Esmagadas",
    "Crème Fraîche": "Crème Fraîche",
    "Cumin Seed": "Sementes de Cominhos",
    "Cumin Seeds": "Sementes de Cominhos",
    "Curry Powder": "Caril em Pó",
    "Dark Chocolate": "Chocolate Negro",
    "Dark Soy Sauce": "Molho de Soja Escuro",
    "Dashi": "Dashi",
    "Desiccated Coconut": "Coco Ralado",
    "Dijon Mustard": "Mostarda Dijon",
    "Dill": "Endro",
    "Ditalini": "Ditalini",
    "Doubanjiang": "Doubanjiang",
    "Double Cream": "Natas",
    "Drained Cannellini Beans": "Feijão Cannellini Escorrido",
    "Drained Cooked Black Beans": "Feijão Preto Cozido e Escorrido",
    "Drained Cooked Butter Beans": "Feijão Manteiga Cozido e Escorrido",
    "Drained Cooked Cannellini Beans": "Feijão Cannellini Cozido e Escorrido",
    "Drained Cooked Chickpeas": "Grão-de-Bico Cozido e Escorrido",
    "Drained Cooked Kidney Beans": "Feijão Vermelho Cozido e Escorrido",
    "Drained Cooked Lentils": "Lentilhas Cozidas e Escorridas",
    "Dried Basil": "Manjericão Seco",
    "Dried Currant": "Groselha Seca",
    "Dried Fruit & Nut Mix": "Mistura de Frutos Secos e Fruta Seca",
    "Dried Instant Yeast": "Fermento Instantâneo Seco",
    "Dried Mixed Herbs": "Ervas Aromáticas Mistas Secas",
    "Dried Oregano": "Orégãos Secos",
    "Dried Parsley": "Salsa Seca",
    "Dried Thyme": "Tomilho Seco",
    "Durum Wheat Semolina Pasta": "Massa de Sêmola de Trigo Duro",
    "Edamame": "Edamame",
    "Egg Noodle": "Noodles de Ovo",
    "Egg White": "Clara de Ovo",
    "English Mustard": "Mostarda Inglesa",
    "Enoki Mushroom": "Cogumelos Enoki",
    "Extra Firm Smoked Tofu": "Tofu Fumado Extra Firme",
    "Extra Mature Cheddar": "Cheddar Extra Curado",
    "Extra Virgin Olive Oil": "Azeite Virgem Extra",
    "Extra-Firm Tofu": "Tofu Extra Firme",
    "Fajita Seasoning": "Tempero de Fajita",
    "Fennel": "Funcho",
    "Fennel Seed": "Sementes de Funcho",
    "Fenugreek Leaf": "Folhas de Feno-Grego",
    "Fenugreek Seeds": "Sementes de Feno-Grego",
    "Feta": "Feta",
    "Fine Salt": "Sal Fino",
    "Firm Tofu": "Tofu Firme",
    "Fish Sauce": "Molho de Peixe",
    "Flaked Almond": "Amêndoa em Lâminas",
    "Flaky Sea Salt": "Sal Marinho em Escamas",
    "Flat Rice Noodle": "Noodles de Arroz Planos",
    "Flatbread": "Pão Pita",
    "Flora": "Flora",
    "Flour": "Farinha",
    "Fresh Basil": "Manjericão Fresco",
    "Fresh Berries": "Frutos Vermelhos Frescos",
    "Fresh Breadcrumbs": "Pão Ralado Fresco",
    "Fresh Chive": "Cebolinho Fresco",
    "Fresh Coriander": "Coentros Frescos",
    "Fresh Dill": "Endro Fresco",
    "Fresh Flat Leaf Parsley": "Salsa de Folha Plana Fresca",
    "Fresh Fruit": "Fruta Fresca",
    "Fresh Ginger": "Gengibre Fresco",
    "Fresh Jalapeño": "Jalapeño Fresco",
    "Fresh Lasagne Sheet": "Folhas de Lasanha Fresca",
    "Fresh Mint": "Hortelã Fresca",
    "Fresh Oregano": "Orégãos Frescos",
    "Fresh Parsley": "Salsa Fresca",
    "Fresh Rosemary": "Alecrim Fresco",
    "Fresh Sage": "Salva Fresca",
    "Fresh Tarragon": "Estragão Fresco",
    "Fresh Thai Basil": "Manjericão Tailandês Fresco",
    "Fresh Thyme": "Tomilho Fresco",
    "Freshly Ground Coffee": "Café Moído Fresco",
    "Fried Shallot": "Chalota Frita",
    "Frozen Banana": "Banana Congelada",
    "Frozen Blackberry": "Amora Congelada",
    "Frozen Blueberries": "Mirtilos Congelados",
    "Frozen Dumplings": "Gyozas Congelados",
    "Frozen French Fry": "Batatas Fritas Congeladas",
    "Frozen Hash Brown": "Hash Brown Congelado",
    "Frozen Mango": "Manga Congelada",
    "Frozen Mixed Berries": "Frutos Vermelhos Mistos Congelados",
    "Frozen Pea": "Ervilhas Congeladas",
    "Frozen Pineapple": "Ananás Congelado",
    "Frozen Raspberry": "Framboesa Congelada",
    "Frozen Shelled Edamame": "Edamame Descascado Congelado",
    "Frozen Spinach": "Espinafres Congelados",
    "Frozen Strawberry": "Morango Congelado",
    "Frozen Sweetcorn": "Milho Doce Congelado",
    "Full-Fat Greek Yoghurt": "Iogurte Grego Gordo",
    "Fusilli": "Fusilli",
    "Garam Masala": "Garam Masala",
    "Garlic Italian Seasoning": "Tempero Italiano de Alho",
    "Garlic Paste": "Pasta de Alho",
    "Garlic Powder": "Alho em Pó",
    "Ghee": "Ghee",
    "Giant Couscous": "Cuscuz Gigante",
    "Ginger": "Gengibre",
    "Ginger Paste": "Pasta de Gengibre",
    "Gnocchi": "Gnocchi",
    "Gochujang": "Gochujang",
    "Golden Breadcrumbs": "Pão Ralado Dourado",
    "Granola": "Granola",
    "Grated Cheddar & Mozzarella Mix": "Mistura de Cheddar e Mozzarella Ralados",
    "Grated Mozzarella": "Mozzarella Ralada",
    "Grated Parmesan": "Parmesão Ralado",
    "Greek Yoghurt": "Iogurte Grego",
    "Green Bean": "Feijão Verde",
    "Green Olive": "Azeitona Verde",
    "Green Salad": "Salada Verde",
    "Ground Cardamom": "Cardamomo em Pó",
    "Ground Cinnamon": "Canela em Pó",
    "Ground Coriander": "Coentros em Pó",
    "Ground Cumin": "Cominhos em Pó",
    "Ground Flaxseed": "Linhaça Moída",
    "Ground Ginger": "Gengibre em Pó",
    "Ground Nutmeg": "Noz-Moscada em Pó",
    "Ground Turmeric": "Cúrcuma em Pó",
    "Ground White Pepper": "Pimenta Branca em Pó",
    "Gruyère": "Gruyère",
    "HP Sauce": "Molho HP",
    "Halloumi": "Halloumi",
    "Harissa Paste": "Pasta de Harissa",
    "Harissa Powder": "Harissa em Pó",
    "Hazelnut": "Avelã",
    "Hemp Seeds": "Sementes de Cânhamo",
    "High-Protein Granola": "Granola Rica em Proteína",
    "Honey": "Mel",
    "Hot Honey": "Mel Picante",
    "Hot Sauce": "Molho Picante",
    "Hummus": "Hummus",
    "Ice": "Gelo",
    "Ice Cube": "Cubo de Gelo",
    "Icing Sugar": "Açúcar em Pó",
    "In Olive Oil": "em Azeite",
    "Instant Coffee": "Café Instantâneo",
    "Instant Noodles": "Noodles Instantâneos",
    "Jasmine Rice": "Arroz Jasmine",
    "Jumbo Oat": "Flocos de Aveia Grandes",
    "Kalamata Olives": "Azeitonas Kalamata",
    "Kale": "Couve Kale",
    "Kashmiri Chilli Powder": "Pimentão Kashmiri",
    "Kasoori Methi": "Kasoori Methi",
    "Kecap Manis": "Kecap Manis",
    "Kefir": "Kefir",
    "Ketchup": "Ketchup",
    "Kewpie Mayonnaise": "Maionese Kewpie",
    "Kidney Bean": "Feijão Vermelho",
    "Kimchi": "Kimchi",
    "King Prawns": "Gambas Grandes",
    "Kiwi": "Kiwi",
    "Korean Chilli Flake": "Flocos de Malagueta Coreana",
    "Korma Curry Paste": "Pasta de Caril Korma",
    "Lamb Mince": "Borrego Picado",
    "Lebanese 7-Spice": "7 Especiarias Libanesas",
    "Leek": "Alho-Francês",
    "Lemon Curd": "Creme de Limão",
    "Lemon Juice": "Sumo de Limão",
    "Lemon Zest": "Raspa de Limão",
    "Lentils": "Lentilhas",
    "Light Coconut Milk": "Leite de Coco Light",
    "Light Cottage Cheese": "Queijo Cottage Light",
    "Light Cream Cheese": "Queijo Creme Light",
    "Light Mayonnaise": "Maionese Light",
    "Light Soft Cheese": "Queijo Fresco Light",
    "Light Soy Sauce": "Molho de Soja Light",
    "Lime": "Lima",
    "Lime Juice": "Sumo de Lima",
    "Lime Pickle": "Pickle de Lima",
    "Lime Wedge": "Gomo de Lima",
    "Long Grain Rice": "Arroz de Grão Longo",
    "Low-Moisture Mozzarella Cheese": "Mozzarella de Baixo Teor de Humidade",
    "MSG": "MSG",
    "Macaroni": "Macarrão",
    "Mackerel": "Cavala",
    "Manchego": "Manchego",
    "Mangetout": "Ervilhas de Quebrar",
    "Mango": "Manga",
    "Mango Chutney": "Chutney de Manga",
    "Maple Syrup": "Xarope de Ácer",
    "Maris Piper Potato": "Batata Maris Piper",
    "Mascarpone": "Mascarpone",
    "Matcha": "Matcha",
    "Mature Cheddar Cheese": "Queijo Cheddar Curado",
    "Mayonnaise": "Maionese",
    "Microwavable Brown Rice": "Arroz Integral de Micro-ondas",
    "Microwave Rice": "Arroz de Micro-ondas",
    "Microwaveable Basmati Rice": "Arroz Basmati de Micro-ondas",
    "Microwaveable Quinoa Pouch": "Saqueta de Quinoa de Micro-ondas",
    "Milk": "Leite",
    "Milled Flaxseed": "Linhaça Moída",
    "Mint": "Hortelã",
    "Mirin": "Mirin",
    "Miso Paste": "Pasta de Miso",
    "Mixed Berries": "Frutos Vermelhos Mistos",
    "Mixed Berry Coulis": "Coulis de Frutos Vermelhos",
    "Mixed Cooked Grains": "Cereais Mistos Cozidos",
    "Mixed Mushroom": "Cogumelos Mistos",
    "Mixed Nuts": "Frutos Secos Mistos",
    "Mixed Olive": "Azeitonas Mistas",
    "Mixed Seeds": "Sementes Mistas",
    "Mixed Spice": "Mistura de Especiarias",
    "Mozzarella": "Mozzarella",
    "Mushroom": "Cogumelos",
    "Mushroom Broth": "Caldo de Cogumelos",
    "Mushroom Stock": "Caldo de Cogumelos",
    "Mustard Powder": "Mostarda em Pó",
    "Mustard Seeds": "Sementes de Mostarda",
    "Napa Cabbage": "Couve Napa",
    "Natural Yoghurt": "Iogurte Natural",
    "Nduja": "Nduja",
    "Neutral Oil": "Óleo Neutro",
    "New Potato": "Batata Nova",
    "Nigella Seed": "Sementes de Nigela",
    "Nori Seaweed": "Alga Nori",
    "Nut Butter": "Manteiga de Frutos Secos",
    "Nutella": "Nutella",
    "Nutmeg": "Noz-Moscada",
    "Nutritional Yeast": "Levedura Nutricional",
    "Oat Bran": "Farelo de Aveia",
    "Oat Milk": "Leite de Aveia",
    "Oats": "Aveia",
    "Olive Oil": "Azeite",
    "Olive Oil Spray": "Spray de Azeite",
    "Onion Powder": "Cebola em Pó",
    "Orange Zest": "Raspa de Laranja",
    "Orecchiette": "Orecchiette",
    "Orzo": "Orzo",
    "Oyster Sauce": "Molho de Ostra",
    "Pak Choi": "Pak Choi",
    "Paneer": "Paneer",
    "Panko Breadcrumbs": "Pão Ralado Panko",
    "Paprika": "Pimentão",
    "Parmesan": "Parmesão",
    "Parsley": "Salsa",
    "Passata": "Passata",
    "Pasta": "Massa",
    "Pasta Water": "Água de Cozer Massa",
    "Patak's Mango Chutney": "Chutney de Manga Patak's",
    "Pea": "Ervilha",
    "Peanut": "Amendoim",
    "Peanut Butter": "Manteiga de Amendoim",
    "Pearl Barley": "Cevada Perlada",
    "Pecans": "Nozes Pecan",
    "Peri Peri Seasoning": "Tempero Peri-Peri",
    "Pesto": "Pesto",
    "Petit Pois": "Ervilhas Petit Pois",
    "Pickle": "Pickle",
    "Pickled Guindilla Chilli": "Malagueta Guindilla em Conserva",
    "Pickled Jalapeño": "Jalapeño em Conserva",
    "Pickled Jalapeño Brine": "Salmoura de Jalapeño",
    "Pickled Red Onion": "Cebola Roxa em Conserva",
    "Pine Nuts": "Pinhões",
    "Pineapple": "Ananás",
    "Piri Piri Seasoning": "Tempero Piri-Piri",
    "Pistachio": "Pistácio",
    "Pitted Date": "Tâmara sem Caroço",
    "Pitted Frozen Cherries": "Cerejas Congeladas sem Caroço",
    "Pitted Medjool Dates": "Tâmaras Medjool sem Caroço",
    "Plain Flour": "Farinha Simples",
    "Plant-Based Protein Powder": "Proteína em Pó de Origem Vegetal",
    "Plum Tomatoes": "Tomates Pelados",
    "Pomegranate Molasses": "Melaço de Romã",
    "Pomegranate Seeds": "Sementes de Romã",
    "Poppy Seed": "Sementes de Papoila",
    "Porcini Mushroom": "Cogumelos Porcini",
    "Pork Belly": "Barriga de Porco",
    "Pork Mince": "Carne Picada de Porco",
    "Portobello Mushroom": "Cogumelos Portobello",
    "Potato": "Batata",
    "Prawn": "Gamba",
    "Prawn Crackers": "Crackers de Gambas",
    "Protein Powder": "Proteína em Pó",
    "Psyllium Husk": "Casca de Psyllium",
    "Pudding Rice": "Arroz para Pudim",
    "Pumpkin Seed": "Sementes de Abóbora",
    "Puy Lentil": "Lentilha Puy",
    "Quinoa": "Quinoa",
    "Radish": "Rabanete",
    "Rainbow Slaw Mix": "Mistura de Coleslaw Colorida",
    "Raisin": "Passa",
    "Ramen Noodle": "Noodles Ramen",
    "Ras el Hanout": "Ras el Hanout",
    "Raspberry": "Framboesa",
    "Raspberry Jam": "Compota de Framboesa",
    "Raw Peeled King Prawn": "Gamba Grande Crua Descascada",
    "Raw Prawn": "Gamba Crua",
    "Red Cabbage": "Couve Roxa",
    "Red Chilli": "Malagueta Vermelha",
    "Red Lentil": "Lentilha Vermelha",
    "Red Miso Paste": "Pasta de Miso Vermelho",
    "Red Onion": "Cebola Roxa",
    "Red Wine": "Vinho Tinto",
    "Red Wine Vinegar": "Vinagre de Vinho Tinto",
    "Reduced-Fat Feta": "Feta Light",
    "Reduced-Fat Red Pesto": "Pesto Vermelho Light",
    "Reserved Butter Bean Liquid": "Líquido Reservado do Feijão Manteiga",
    "Rhubarb": "Ruibarbo",
    "Rice Vinegar": "Vinagre de Arroz",
    "Rice Wine Vinegar": "Vinagre de Vinho de Arroz",
    "Rigatoni": "Rigatoni",
    "Roasted Almond": "Amêndoa Torrada",
    "Roasted Peanuts": "Amendoins Torrados",
    "Roasted Red Pepper": "Pimento Vermelho Assado",
    "Rocket": "Rúcula",
    "Rolled Oat": "Flocos de Aveia",
    "Romaine Lettuce": "Alface Romaine",
    "Rosemary": "Alecrim",
    "Salmon": "Salmão",
    "Salmon Fillet": "Filete de Salmão",
    "Salsa": "Salsa",
    "Salt": "Sal",
    "Salted Butter": "Manteiga com Sal",
    "Salted Peanuts": "Amendoins Salgados",
    "Salted Roasted Peanut": "Amendoim Torrado e Salgado",
    "Sambal": "Sambal",
    "Sambal Oelek": "Sambal Oelek",
    "Sausage": "Salsicha",
    "Savoy Cabbage": "Couve Savoy",
    "Sea Salt": "Sal Marinho",
    "Self Raising Flour": "Farinha com Fermento",
    "Semi-Skimmed Milk": "Leite Meio-Gordo",
    "Sesame Oil": "Óleo de Sésamo",
    "Sesame Seeds": "Sementes de Sésamo",
    "Shaoxing Wine": "Vinho Shaoxing",
    "Shelled Edamame": "Edamame Descascado",
    "Shelled Hemp Seeds": "Sementes de Cânhamo Descascadas",
    "Sherry Vinegar": "Vinagre de Xerez",
    "Shichimi Togarashi": "Shichimi Togarashi",
    "Shiitake Mushroom": "Cogumelos Shiitake",
    "Shoyu Soy Sauce": "Molho de Soja Shoyu",
    "Silken Tofu": "Tofu Sedoso",
    "Single Cream": "Natas Simples",
    "Sirloin Steak": "Bife de Lombo",
    "Skimmed Milk": "Leite Magro",
    "Skin-On Salmon Fillet": "Filete de Salmão com Pele",
    "Skinless Chicken Thigh": "Coxa de Frango sem Pele",
    "Skinless Salmon Fillet": "Filete de Salmão sem Pele",
    "Skyr Natural Yoghurt": "Skyr Natural",
    "Slivered Almonds": "Amêndoas em Lâminas",
    "Smoked Mackerel": "Cavala Fumada",
    "Smoked Paprika": "Pimentão Fumado",
    "Smoked Streaky Bacon": "Bacon Fumado",
    "Smoked Tempeh": "Tempeh Fumado",
    "Smoked Tofu": "Tofu Fumado",
    "Smoked Trout": "Truta Fumada",
    "Smooth Peanut Butter": "Manteiga de Amendoim Suave",
    "Soft Cheese": "Queijo Fresco",
    "Soft Light Brown Sugar": "Açúcar Mascavado Claro",
    "Sour Cream": "Natas Azedas",
    "Sour Cream & Chive Dip": "Molho de Natas Azedas com Cebolinho",
    "Sourdough": "Pão de Massa Mãe",
    "Soy Sauce": "Molho de Soja",
    "Soya Milk": "Leite de Soja",
    "Spaghetti": "Esparguete",
    "Spicy Chorizo": "Chouriço Picante",
    "Spinach": "Espinafres",
    "Spring Onion": "Cebolinha",
    "Sriracha": "Sriracha",
    "Stir-Fry Vegetable Mix": "Mistura de Legumes para Stir-Fry",
    "Strawberry": "Morango",
    "Strawberry Jam": "Compota de Morango",
    "Strong White Bread Flour": "Farinha de Trigo Forte",
    "Sugar": "Açúcar",
    "Sugar Snap Pea": "Ervilhas Tortas",
    "Sumac": "Sumagre",
    "Sun-Dried Tomato": "Tomate Seco",
    "Sun-Dried Tomato Oil": "Óleo de Tomate Seco",
    "Sun-Dried Tomato Pesto": "Pesto de Tomate Seco",
    "Sunflower Oil": "Óleo de Girassol",
    "Sunflower Seeds": "Sementes de Girassol",
    "Sushi Rice": "Arroz de Sushi",
    "Sweet Chilli Sauce": "Molho Doce de Malagueta",
    "Sweet Potato": "Batata-Doce",
    "Sweetcorn": "Milho Doce",
    "Tabasco": "Tabasco",
    "Tahini": "Tahini",
    "Tamarind Paste": "Pasta de Tamarindo",
    "Tempeh": "Tempeh",
    "Tenderstem Broccoli": "Brócolos Tenderstem",
    "Teriyaki Sauce": "Molho Teriyaki",
    "Thai Basil": "Manjericão Tailandês",
    "Thai Green Curry Paste": "Pasta de Caril Verde Tailandês",
    "Thai Red Curry Paste": "Pasta de Caril Vermelho Tailandês",
    "Thai Yellow Curry Paste": "Pasta de Caril Amarelo Tailandês",
    "Third of Peanut Curry Sauce": "Terço do Molho de Caril de Amendoim",
    "Toasted Coconut Flake": "Flocos de Coco Tostado",
    "Toasted Flaked Almonds": "Amêndoas em Lâminas Tostadas",
    "Toasted Sesame Oil": "Óleo de Sésamo Tostado",
    "Toasted Sesame Seed": "Sementes de Sésamo Tostadas",
    "Toasted Sesame Seeds": "Sementes de Sésamo Tostadas",
    "Tomato": "Tomate",
    "Tomato Ketchup": "Ketchup de Tomate",
    "Tomato Pasta Sauce": "Molho de Tomate para Massa",
    "Tomato Purée": "Concentrado de Tomate",
    "Tuna": "Atum",
    "Tuna in Spring Water": "Atum em Água",
    "Udon Noodle": "Noodles Udon",
    "Undyed Smoked Haddock": "Hadoque Fumado Natural",
    "Unsalted Butter": "Manteiga sem Sal",
    "Unsweetened Almond Milk": "Leite de Amêndoa sem Açúcar",
    "Unsweetened Soy Milk": "Leite de Soja sem Açúcar",
    "Vanilla Essence": "Essência de Baunilha",
    "Vanilla Extract": "Extrato de Baunilha",
    "Vanilla Greek Yoghurt": "Iogurte Grego de Baunilha",
    "Vanilla Protein Powder": "Proteína em Pó de Baunilha",
    "Vegan Burrata": "Burrata Vegan",
    "Vegan Butter": "Manteiga Vegan",
    "Vegan Cheese": "Queijo Vegan",
    "Vegan Chocolate": "Chocolate Vegan",
    "Vegan Cream Cheese": "Queijo Creme Vegan",
    "Vegan Fish Sauce": "Molho de Peixe Vegan",
    "Vegan Mayonnaise": "Maionese Vegan",
    "Vegan Vanilla Protein Powder": "Proteína em Pó de Baunilha Vegan",
    "Vegan Yoghurt": "Iogurte Vegan",
    "Vegetable Bouillon Power": "Caldo de Legumes em Pó",
    "Vegetable Oil": "Óleo Vegetal",
    "Vegetable Oil Spray": "Spray de Óleo Vegetal",
    "Vegetable Stock": "Caldo de Legumes",
    "Vine Tomato": "Tomate de Videira",
    "Vodka": "Vodka",
    "Walnut": "Noz",
    "Warm Water": "Água Morna",
    "Water": "Água",
    "Watercress": "Agrião",
    "White Cabbage": "Couve Branca",
    "White Miso": "Miso Branco",
    "White Sesame Seed": "Sementes de Sésamo Branco",
    "White Sugar": "Açúcar Branco",
    "White Wine": "Vinho Branco",
    "White Wine Vinegar": "Vinagre de Vinho Branco",
    "Whole Flaxseed": "Linhaça Inteira",
    "Whole Milk": "Leite Gordo",
    "Wholegrain Mustard": "Mostarda de Grão Inteiro",
    "Wholewheat Pasta": "Massa Integral",
    "Worcestershire Sauce": "Molho Worcestershire",
    "XO Sauce": "Molho XO",
    "Yoghurt": "Iogurte",
    "ZOE Daily30+": "ZOE Daily30+",
    "Za'atar": "Za'atar",
    "Za\u2019atar": "Za'atar",
    # lowercase / mixed case variants
    "american Cheese": "Queijo Americano",
    "anchovy": "Anchova",
    "apple": "Maçã",
    "aubergine": "Beringela",
    "avocado": "Abacate",
    "baby Cucumber": "Mini Pepino",
    "baby Potato": "Batata Baby",
    "bagel": "Bagel",
    "banana": "Banana",
    "banana Shallot": "Chalota",
    "bay Leaf": "Folha de Louro",
    "beef Meatball": "Almôndega de Carne",
    "bell Pepper": "Pimento",
    "birds Eye Green Chilli": "Malagueta Verde Bird's Eye",
    "biscoff Biscuit": "Bolacha Biscoff",
    "blood Orange": "Laranja Sanguínea",
    "bone -In Skin-On Chicken Thigh": "Coxa de Frango com Osso e Pele",
    "boneless Skin-On Salmon Fillet": "Filete de Salmão sem Osso com Pele",
    "boneless Skinless Chicken Thigh": "Coxa de Frango sem Osso e sem Pele",
    "brioche Bun": "Pãozinho Brioche",
    "broccoli": "Brócolos",
    "brown Onion": "Cebola Castanha",
    "bulb Fennel": "Bolbo de Funcho",
    "butter Brioche Roll": "Brioche de Manteiga",
    "butternut Squash": "Abóbora Butternut",
    "cabbage": "Couve",
    "cardamom Pod": "Vagem de Cardamomo",
    "carrot": "Cenoura",
    "cauliflower": "Couve-Flor",
    "celery": "Aipo",
    "cherry Tomatoes": "Tomates Cherry",
    "chicken Breast": "Peito de Frango",
    "chicken Stock Cube": "Cubo de Caldo de Frango",
    "cinnamon Stick": "Pau de Canela",
    "clove": "Cravo",
    "clove Garlic": "Dente de Alho",
    "clove Garlic Clove": "Dente de Alho",
    "cm Ginger": "Gengibre",
    "corn Tortilla": "Tortilha de Milho",
    "courgette": "Courgette",
    "crumpet": "Crumpet",
    "cucumber": "Pepino",
    "curry Leaf": "Folha de Caril",
    "demi -Baguette": "Meia Baguete",
    "dried Bay Leaf": "Folha de Louro Seca",
    "egg": "Ovo",
    "egg White": "Clara de Ovo",
    "egg Yolk": "Gema de Ovo",
    "eggs": "Ovos",
    "english Breakfast Teabag": "Saqueta de Chá English Breakfast",
    "english Muffin": "Muffin Inglês",
    "flatbread": "Pão Pita",
    "flour Tortilla": "Tortilha de Farinha",
    "fresh Jalapeño": "Jalapeño Fresco",
    "frozen Strawberry": "Morango Congelado",
    "garlic": "Alho",
    "garlic Clove": "Dente de Alho",
    "gherkin": "Pepininho em Conserva",
    "green Apple": "Maçã Verde",
    "green Bell Pepper": "Pimento Verde",
    "green Cardamom Pod": "Vagem de Cardamomo Verde",
    "green Chilli": "Malagueta Verde",
    "green Finger Chilli": "Malagueta Verde Comprida",
    "hispi Cabbage": "Couve Hispi",
    "iceberg Lettuce": "Alface Iceberg",
    "jalape ño": "Jalapeño",
    "jarred Grilled Red Peppers": "Pimentos Vermelhos Grelhados em Frasco",
    "jarred Red Pepper": "Pimento Vermelho em Frasco",
    "kalamata Olives": "Azeitonas Kalamata",
    "kiwi": "Kiwi",
    "large Tomato": "Tomate Grande",
    "leaf Sage": "Folha de Salva",
    "leek": "Alho-Francês",
    "lemon": "Limão",
    "lemon Juice": "Sumo de Limão",
    "lemon Wedge": "Gomo de Limão",
    "lettuce": "Alface",
    "lime": "Lima",
    "lime Wedge": "Gomo de Lima",
    "medjool Date": "Tâmara Medjool",
    "naan": "Naan",
    "nest Fresh Wheat Noodles": "Noodles de Trigo Fresco",
    "nutmeg": "Noz-Moscada",
    "onion": "Cebola",
    "orange": "Laranja",
    "pak Choi": "Pak Choi",
    "patak 's Tikka Masala Paste Pots": "Pasta de Tikka Masala Patak's",
    "pepper": "Pimento",
    "pineapple": "Ananás",
    "pitta": "Pão Pita",
    "plantain": "Plantano",
    "pork Chop": "Costeleta de Porco",
    "pork Sausage": "Salsicha de Porco",
    "portobello Mushroom": "Cogumelo Portobello",
    "potato": "Batata",
    "rasher Bacon": "Fatia de Bacon",
    "rasher Smoked Streaky Bacon": "Fatia de Bacon Fumado",
    "rasher Streaky Bacon": "Fatia de Bacon",
    "red Bell Pepper": "Pimento Vermelho",
    "red Bird's Eye Chilli": "Malagueta Bird's Eye Vermelha",
    "red Chilli": "Malagueta Vermelha",
    "red Onion": "Cebola Roxa",
    "red Pepper": "Pimento Vermelho",
    "ripe Banana": "Banana Madura",
    "roasted Red Pepper": "Pimento Vermelho Assado",
    "romaine Lettuce": "Alface Romaine",
    "romano Pepper": "Pimento Romano",
    "roti": "Roti",
    "sausage": "Salsicha",
    "scotch Bonnet Chilli": "Malagueta Scotch Bonnet",
    "shallot": "Chalota",
    "sheet Nori Seaweed": "Folha de Alga Nori",
    "shiitake Mushroom": "Cogumelo Shiitake",
    "skinless Chicken Thigh": "Coxa de Frango sem Pele",
    "skinless Salmon Fillet": "Filete de Salmão sem Pele",
    "slice Bread": "Fatia de Pão",
    "slice Brown Bread": "Fatia de Pão Integral",
    "slice Cheddar Cheese": "Fatia de Queijo Cheddar",
    "slice Crusty Bread": "Fatia de Pão Crocante",
    "slice Ham": "Fatia de Fiambre",
    "slice Seeded Bread": "Fatia de Pão com Sementes",
    "slice Soft White Bread": "Fatia de Pão Branco Macio",
    "slice Sourdough": "Fatia de Pão de Massa Mãe",
    "small Corn Tortilla": "Tortilha de Milho Pequena",
    "small Flour Tortilla": "Tortilha de Farinha Pequena",
    "spring Onion": "Cebolinha",
    "square Dark Chocolate": "Quadrado de Chocolate Negro",
    "star Anise": "Anis Estrelado",
    "stick Celery": "Talo de Aipo",
    "sweet Gem Lettuce": "Alface Sweet Gem",
    "sweet Potato": "Batata-Doce",
    "sweetheart Cabbage": "Couve Sweetheart",
    "tabtbsp Sesame Seeds": "Sementes de Sésamo",
    "thigh Bone-In Skin-On Chicken Thigh": "Coxa de Frango com Osso e Pele",
    "tomato": "Tomate",
    "tortilla": "Tortilha",
    "vegetable Gyoza": "Gyoza de Legumes",
    "vegetable Stock Cube": "Cubo de Caldo de Legumes",
    "vine Tomato": "Tomate de Videira",
    "white Onion": "Cebola Branca",
    "wrap Nori Seaweed": "Alga Nori para Wrap",
    "x 145 Can Tuna": "Lata de Atum",
    "yellow Bell Pepper": "Pimento Amarelo",
}

UNIT_TRANSLATIONS = {
    "tsp": "c. chá",
    "tbsp": "c. sopa",
    "g": "g",
    "kg": "kg",
    "ml": "ml",
    "l": "l",
    "can": "lata",
    "jar": "frasco",
    "fillet": "filete",
    "head": "cabeça",
    "knob": "noz",
    "pinch": "pitada",
    "pouch": "saqueta",
    "sprig": "ramo",
    "stalk": "talo",
}

def translate_unit(unit):
    if unit is None:
        return None
    if unit in UNIT_TRANSLATIONS:
        return UNIT_TRANSLATIONS[unit]
    print(f"  WARNING: no unit translation for '{unit}'")
    return unit

def translate_item(item):
    if item in TRANSLATIONS:
        return TRANSLATIONS[item]
    # fallback: return original if not found (log it)
    print(f"  WARNING: no translation for '{item}'")
    return item

files = sorted(f for f in os.listdir(base) if f.endswith('.json'))
total = 0
skipped = 0

for filename in files:
    path = os.path.join(base, filename)
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    parsed = data.get('ingredientsParsed', [])
    if not parsed:
        skipped += 1
        continue

    # Build translated ingredientsParsed
    translated_parsed = []
    for ing in parsed:
        translated_parsed.append({
            "amount": ing.get("amount"),
            "unit": translate_unit(ing.get("unit")),
            "item": translate_item(ing["item"]) if ing.get("item") else None
        })

    # Ensure i18n.pt exists
    data.setdefault('i18n', {}).setdefault('pt', {})
    data['i18n']['pt']['ingredientsParsed'] = translated_parsed

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    total += 1

print(f'\nDone! Updated {total} files, skipped {skipped}.')
