#!/bin/bash
# Download all 100 breakfast recipe images from Chef António Duarte's website

base_url="https://pequeno-almoco.chefantonioduarte.com/recipes"

# All 100 recipe image filenames from the website
images=(
  "panquecas-banana-aveia.jpg"
  "overnight-oats.jpg"
  "muffins-cenoura.jpg"
  "smoothie-bowl-verde.jpg"
  "energy-balls-cacau.jpg"
  "panquecas-batata-doce.jpg"
  "pudim-chia-manga.jpg"
  "granola-caseira.jpg"
  "wrap-alface-frango.jpg"
  "bolachas-aveia-coco.jpg"
  "smoothie-abacate-cacau.jpg"
  "tapioca-ovo-espinafres.jpg"
  "mousse-abacate-cacau.jpg"
  "barrinhas-sementes.jpg"
  "papas-aveia-maca.jpg"
  "acai-bowl.jpg"
  "frittatas-batata-doce.jpg"
  "crepes-farinha-arroz.jpg"
  "barras-tamaras-amendoa.jpg"
  "ovos-abacate.jpg"
  "smoothie-manga-maracuja.jpg"
  "beiju-recheado.jpg"
  "bolo-banana-coco.jpg"
  "pimentos-recheados.jpg"
  "gelado-banana.jpg"
  "mingau-trigo-sarraceno.jpg"
  "panqueca-grao-bico.jpg"
  "pudim-chia-kiwi.jpg"
  "cubos-batata-doce-maca.jpg"
  "muffins-espinafre-banana.jpg"
  "tostas-arroz-abacate.jpg"
  "parfait-iogurte-coco.jpg"
  "bolinhoslegumes.jpg"
  "sumo-verde-detox.jpg"
  "mini-pizzas-tapioca.jpg"
  "waffles-aveia-salgados.jpg"
  "copinhos-chocolate-amendoa.jpg"
  "tofu-mexido.jpg"
  "cookies-banana-sementes.jpg"
  "overnight-pessego-pistachio.jpg"
  "humus-batata-doce.jpg"
  "rolinhos-papel-arroz-camarao.jpg"
  "maca-assada-crumble.jpg"
  "smoothie-acai-berry.jpg"
  "muffins-ovo-legumes.jpg"
  "bowl-quinoa-ovo.jpg"
  "panquecas-farinha-coco.jpg"
  "crackers-sementes-alecrim.jpg"
  "chips-banana-da-terra.jpg"
  "golden-milk.jpg"
  "tamaras-recheadas.jpg"
  "torrada-batata-doce.jpg"
  "bark-iogurte-coco.jpg"
  "omelete-grao-bico.jpg"
  "compota-framboesa-chia.jpg"
  "crepes-farinha-arroz-morangos.jpg"
  "acai-bowl-granola.jpg"
  "granola-caseira.jpg"
  "panquecas-batata-doce.jpg"
  "pudim-chia-manga-maracuja.jpg"
  "pimentos-recheados.jpg"
  "smoothie-abacate-cacau.jpg"
  "wrap-alface-frango.jpg"
  "bolachas-aveia-coco.jpg"
  "mini-frittatas-batata-doce.jpg"
  "tapioca-ovo-espinafres.jpg"
  "gelado-banana.jpg"
  "beiju-recheado.jpg"
  "papas-aveia-maca.jpg"
  "ovos-abacate.jpg"
  "barras-tamaras-amendoa.jpg"
  "mousse-abacate-cacau.jpg"
  "smoothie-manga-maracuja.jpg"
  "barrinhas-sementes.jpg"
  "bolo-banana-coco.jpg"
  "mingau-sarraceno-pera.jpg"
  "pataniscas-abobrinha.jpg"
  "pudim-chia-coco-maracuja.jpg"
  "batata-doce-recheada.jpg"
  "muffins-espinafre-maca.jpg"
  "rolinhos-papel-arroz-salmao.jpg"
  "overnight-cenoura.jpg"
  "tabule-couve-flor.jpg"
  "picoletas-banana-chocolate.jpg"
  "ovos-mexidos-cogumelos.jpg"
  "socca-grao-bico.jpg"
  "parfait-iogurte-coco.jpg"
  "sopa-batata-doce-lentilhas.jpg"
  "crackers-linhaca.jpg"
  "bowl-quinoa-kale.jpg"
  "chips-maca.jpg"
  "cogumelos-recheados.jpg"
  "compota-mirtilo-chia.jpg"
  "energy-balls-cenoura.jpg"
  "muffins-ovo-brocolis.jpg"
  "trufas-abacate-cacau.jpg"
  "crepes-sarraceno-cogumelos.jpg"
  "picoletas-frutos-vermelhos.jpg"
  "hash-batata-doce.jpg"
  "matcha-latte.jpg"
)

count=0
total=${#images[@]}

echo "Downloading $total recipe images..."
echo ""

for img in "${images[@]}"; do
  ((count++))
  if [ ! -f "$img" ]; then
    echo "[$count/$total] Downloading $img..."
    curl -s -o "$img" "$base_url/$img"
    if [ $? -eq 0 ]; then
      echo "  ✓ Downloaded successfully"
    else
      echo "  ✗ Failed to download"
    fi
  else
    echo "[$count/$total] Skipping $img (already exists)"
  fi
done

echo ""
echo "Done! Downloaded recipe images."
echo ""
echo "Summary:"
ls -1 *.jpg 2>/dev/null | wc -l | xargs echo "Total images:"
